### ISSUE TITLE
hdfs_port_namenode_http is incorrectly set if HDFS package are not installed using cesnet-hadoop

### ISSUE THREAD

**Issue by eLvErDe** [MetaCenterCloudPuppet/cesnet-hadoop#14]
Hello,

Following snippet from manifests/init.pp is not working correcly for me and imho, is incorrect.

```ruby
  case "${::hadoop::version}." {
    /^2(\.)?/: {
      $hdfs_port_namenode_http = '50070'
      $hdfs_port_namenode_https = '50470'
      $hdfs_port_namenode = '8020'
    }
    default: {
      $hdfs_port_namenode_http = '9870'
      $hdfs_port_namenode_https = '9871'
      # changed back from 9820 to 8020 in Hadoop 3.0.1
      $hdfs_port_namenode = '8020'
    }
  }
```

If HDFS has been deployed manually, without using the class itself ::hadoop:version is undefined and thus, defaults to hadoop 3.x port, which is, in my case, incorrect.

Would you at least provide a way to override these ports from class parameters ?

Best regards, Adam.

**Comment by valtri** [comment]
Added parameters for HDFS ports (master only).

For non-HA HDFS cluster could used the `defaultFS` parameter. Or any property can be override using `properties` parameter.

**Comment by eLvErDe** [comment]
Thanks, that was fast :D

**Comment by eLvErDe** [comment]
Deployed and confirmed working, thanks.
