### ISSUE TITLE
Failed to parse template hadoop/hadoop/core-site.xml.erb

### ISSUE THREAD

**Issue by becker-IT** [MetaCenterCloudPuppet/cesnet-hadoop#2]
Hello,
I try to run hadoop on a CentOS box and fail at the very beginning: 

# puppet  agent -t 
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse template hadoop/hadoop/core-site.xml.erb:
  Filepath: /etc/puppet/modules/hadoop/templates/hadoop/core-site.xml.erb
  Line: 32
  Detail: private method `select' called for nil:NilClass
 at /etc/puppet/modules/hadoop/manifests/common/config.pp:11 on node hhvmsparkqat01.easycash.de
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by valtri** [comment]
Yes, CentOS is not supported by this module. The problem here is the language constructs in templates requires at least ruby 1.9.

But as I'm looking at it now, maybe it could be rewritten without select()...

**Comment by valtri** [comment]
Fixed the syntax problem in git master, ruby <= 1.8 is now supported.

CentOS will require more work yet:
1) I think there is a bug in Cloudera cdh5.4.2 (file /usr/lib/hadoop-hdfs/bin/hdfs)
2) templates with environment variables still need tuning (distinguish Fedora/CentOS(RHEL))
