### ISSUE TITLE
mapreduce.jobhistory.webapps.address typo

### ISSUE THREAD

**Issue by martinco** [MetaCenterCloudPuppet/cesnet-hadoop#3]
Hi,

Thank you for this module.

Confirming with the docs: https://hadoop.apache.org/docs/r2.7.2/hadoop-mapreduce-client/hadoop-mapreduce-client-core/mapred-default.xml#mapreduce.jobhistory.webapp.address

It appears there is a typo in manifests/init.pp#217

    - 'mapreduce.jobhistory.webapps.address' => "${hs_hostname}:19888",
    + 'mapreduce.jobhistory.webapp.address' => "${hs_hostname}:19888",

**Comment by valtri** [comment]
Yes, there is a typo. The funny thing is History Server still works good without the proper option set (I would say even better, because https version should have different port), and default value 0.0.0.0 covers multi-homing usage. It can be probably safely removed. Thanks for reporting it!

**Comment by valtri** [comment]
Fixed in cesnet-hadoop 2.4.1.
