### ISSUE TITLE
Illegal fully qualified name with parser = future

### ISSUE THREAD

**Issue by eLvErDe** [MetaCenterCloudPuppet/cesnet-hadoop#6]
Hello,

Latest version of the module seems to fail with future parser:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Illegal fully qualified name in file /etc/puppet/environments/production/modules/zookeeper/manifests/config.pp at line 60:38 at /etc/puppet/environments/production/modules/zookeeper/manifests/init.pp:52:3 on node hdfs-master1.service.earthlab.lu

The same occurs at line 67.

It seems that replacing with content => "${_myid}" fixes the issue (for me) but it may have broken something else.

Best regards, Adam.

**Comment by eLvErDe** [comment]
Sorry, this ticket should habe been created against zookeeper module.

The same issue occurs in hadoop module at line 508.

I made the following modification to get it applied: 
#'nfs.kerberos.principal' => "${hadoop::_nfs_proxy_user}/_HOST@${hadoop::realm}",
'nfs.kerberos.principal' => "${_nfs_proxy_user}/_HOST@${hadoop::realm}",

**Comment by valtri** [comment]
Hello,

what version of puppet do you have? In case of zookeeper, the future parser is tested automatically (although only as simulated run using rspec-puppet and with puppet 3.x)...

**Comment by eLvErDe** [comment]
Hello,

I'm using Debian stable, so puppet 3.7.2.
I'll be working on Puppet stuff all day so feel free to ask for any test if needed.

Best regards, Adam.

**Comment by valtri** [comment]
Theoretically it could be used something like (to keep it portable for real puppet 4):

`$args = sprintf('--myid %s', $::zookeeper::_myid)`

But, it looks like the future parser in puppet 3.7 in Debian 8 has more issues. For example any validate_* function from stdlib returns error:

```
Error: Evaluation Error: Error while evaluating a Function Call, undefined method `repeated_param' for #<Puppet::Functions::DispatcherBuilder:0x00000003838b20> at /etc/puppet/modules/apt/manifests/init.pp:36:3 on node myriad1.zcu.cz
```

Maybe there should not be support for future parser at all in hadoop/zookeeper modules (from puppet 3.7). I'm interested in puppet 4 itself of course.

**Comment by valtri** [comment]
Puppet 4 directly seems working fine with cesnet-hadoop module. I'm closing this issue.
