### ISSUE TITLE
Support for CDH 6

### ISSUE THREAD

**Issue by marvi** [MetaCenterCloudPuppet/cesnet-hadoop#8]
CDH 6 is released (https://archive.cloudera.com/cdh6/6.0.0/). Do you have plans to support it?

**Comment by marvi** [comment]
I have been playing a little with it and it seems to work. I think there is a bug in CDH that prevents HDFS cli command to work, out of the box. I reported it as https://issues.cloudera.org/browse/DISTRO-895. With my workaround I was able to set up a namenode and some datanodes with Vagrant and CentOS. I have tried HDFS, Hive and Spark 2.2 from CDH. Next is Hue.

**Comment by marvi** [comment]
The hdfs bug (DISTRO-895) is fixed in CDH 6.1.

**Comment by valtri** [comment]
Support for Hadoop >= 3.0.0 released in cesnet-hadoop v2.5.0.

There is a new parameter `hadoop::version` with default value "2". Value "3" (or "3.x", ...) will activate some fine tuning for Hadoop >= 3.0.0 - different default ports, workaround in NFS startup script, replacing some deprecated (but still working) properties.

Testing and modifying of CESNET modules providing addons are not finished (Hive and HBase seems to work, Hue needs update, Spark and Oozie not tested yet).
